### ISSUE TITLE
db-mainnavigation is completely broken below 1023 px viewport

### ISSUE THREAD

**Issue by mriehl** [db-ui/elements#1964]
When viewing the [db-mainnavigation](https://db-ui.github.io/elements/?path=/story/02-navigation-main-navigation-intro--page) component in the storybook and resizing the window to be less than 1023px width the menu will completely disappear.
I tested this in Chrome and Safari, not sure about Firefox.

![menu-below-1023px](https://github.com/db-ui/elements/assets/1955590/becfa093-5351-42dc-8b43-40e7c6a20d7e)
![menu-above-1023px](https://github.com/db-ui/elements/assets/1955590/7681297d-098a-4aa8-b40a-e302c0f23fa8)

There are various `display: none` styles attached to it conditionally.

Patching the core css with

```css
@media screen and (max-width: 1023px) {
  .cmp-mainnavigation > ul {
    display: block !important;
  }
}
```

at least makes it "somewhat" useable but obviously patching the CSS is an awful solution I don't want to rely on.
Could you please check if the current css behaviour is really correct.
